minio:
  endpoint_url: localhost:19000
  aws_access_key_id: xxx
  aws_secret_access_key: xxx
webhook:
  tokens:
    - xxx
postgres:
  host: 127.0.0.1
  port: 5432
  database: postgres
  user: postgres
  password: xxx